### ISSUE TITLE
The lighting devices will be added as light entities

### ISSUE THREAD

**Issue by niksefluen** [tomplayford/homeassistant_helvar#2]
Hi, first I just want to say thank you very much for taking the time to create this integration. However, I have a few questions. I can't get the lights in as light entities; I only get my router 910 and all groups.

**Comment by nextgennestkft** [comment]
I have the same problem. Do you have any update?

**Comment by tomplayford** [comment]
@nextgennestkft - what do the logs say? Can you post the complete log dump?

**Comment by Glerupking** [comment]
i have the save issue with the devices 

can u help with this or is it out of your hands

i have even tried to add the aiohevler file in to the normal custom compuntens file, but i feel like it didnt work

best regrades 
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/helvar/select.py:46
integration: Helvar
First occurred: 10:37:52 AM (29 occurrences)
Last logged: 10:43:44 AM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1065, in _async_update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 978, in async_update_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 145, in state
    current_option = self.current_option
                     ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/helvar/select.py", line 46, in current_option
    current_scene = self.router.api.scenes.get_scene(current_scene_address)
  File "/usr/local/lib/python3.13/site-packages/aiohelvar/scenes.py", line 36, in get_scene
    return self.scenes[scene_address]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: <aiohelvar.parser.address.SceneAddress object at 0x7f7d8ccec0>

**Comment by tomplayford** [comment]
This should be fixed now - or at least it'll be a different error. If you still get an error, please share it here. I'll close this for now.
